-------------CREATE DATABASE-------------
CREATE TABLE NHACUNGCAP (
    MANCC CHAR(5) PRIMARY KEY,
    TENNCC NVARCHAR2(300),
    DIACHINCC CHAR(300),
    SDTNCC CHAR(11),
    EMAILNCC CHAR(255),
    WEBNCC CHAR(300)
)

CREATE TABLE LOAIKH (
    MALOAIKH CHAR(5) PRIMARY KEY,
    TENLOAIKH NVARCHAR2(30),
    CHIETKHAU FLOAT
)

CREATE TABLE PHANLOAI (
    MAPL CHAR(5) PRIMARY KEY,
    TENPL NVARCHAR2(50)
)

CREATE TABLE CHUCVU (
    MACV CHAR(5) PRIMARY KEY,
    TENCV NVARCHAR2(50)
)

CREATE TABLE KHACHHANG (
    MAKH CHAR(5) PRIMARY KEY,
    HO NVARCHAR2(100),
    TEN NVARCHAR2(100),
    GIOITINH NVARCHAR2(5),
    SDT CHAR(11),
    DIACHI NVARCHAR2(300),
    MALOAIKH CHAR(5),
    FOREIGN KEY (MALOAIKH) REFERENCES LOAIKH(MALOAIKH)
)

CREATE TABLE NHANVIEN (
    MANV CHAR(5) PRIMARY KEY,
    HONV NVARCHAR2(100),
    TENNV NVARCHAR2(100),
    GIOITINH NVARCHAR2(5),
    SDTNV CHAR(11),
    DIACHINV CHAR(300),
    MACV CHAR(5),
    FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV)
)

CREATE TABLE SANPHAM (
    MASP CHAR(5) PRIMARY KEY,
    TENSP NVARCHAR2(100),
    GIABAN INT,
    MAPL CHAR(5),
    MANCC CHAR(5),
    FOREIGN KEY (MAPL) REFERENCES PHANLOAI(MAPL),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
)

CREATE TABLE KHOHANG (
    STT INT PRIMARY KEY,
    MAKHO CHAR(5),
    SLTON INT,
    MASP CHAR(5),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)

CREATE TABLE HOADON (
    MAHD CHAR(5) PRIMARY KEY,
    NGAYTAOHD DATE,
    MANV CHAR(5),
    MAKH CHAR(5),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTHD (
    MASP CHAR(5),
    MAHD CHAR(5),
    SLMUA INT,
    PRIMARY KEY (MASP, MAHD),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
)
